#
#--------------------------------------------------------------------------
# Image Setup
#--------------------------------------------------------------------------
#

FROM node:6.11.4-alpine

MAINTAINER Donny Arieffian <donny.arieffian@gmail.com>

EXPOSE 8888