#
#--------------------------------------------------------------------------
# Image Setup
#--------------------------------------------------------------------------
#

FROM php:7.1-fpm

LABEL maintainer ="donny.arieffian@gmail.com"

#
#--------------------------------------------------------------------------
# PHP Extension Installation
#--------------------------------------------------------------------------
#

RUN apt-get update && \
    apt-get install -y  tzdata \
                        openssl \
                        libssl-dev \
                        build-essential \
                        libfreetype6 \
                        libjpeg62-turbo \
                        libfreetype6-dev \
                        libpng-dev \
                        libjpeg62-turbo-dev \
                        xml-core \
                        redis-tools \
                        mcrypt \
                        libzip-dev \
                        zip \
                        && rm -rf /var/lib/apt/lists/*

# Install the PHP pdo_mysql
RUN docker-php-ext-install pdo_mysql && \
# Install the PHP gd library
  docker-php-ext-configure gd \
    --with-gd \
    --with-freetype-dir=/usr/include/ \
    --with-png-dir=/usr/include/ \
    --with-jpeg-dir=/usr/include/ && \
  NPROC=$(grep -c ^processor /proc/cpuinfo 2>/dev/null || 1) && \
  docker-php-ext-install -j${NPROC} gd &&\
# Install the PHP redis
  pecl install -o -f redis && \
  docker-php-ext-enable redis && \
# Install the PHP grpc
  pecl install grpc && \
  docker-php-ext-enable grpc && \
# Install the PHP protobuf
  pecl install protobuf && \
  docker-php-ext-enable protobuf && \
# Install the PHP mongodb
  pecl install mongodb && \
  docker-php-ext-enable mongodb && \
# Install the PHP opcache
  docker-php-ext-install opcache && \
# Install the PHP zip
  docker-php-ext-configure zip --with-libzip && \
  docker-php-ext-install zip && \
# Install the PHP xdebug
  pecl install xdebug && \
  docker-php-ext-enable xdebug && \
# Install the PHP sockets
  docker-php-ext-install sockets && \
# Cleaning up
  rm -rf /tmp/pear

#
#--------------------------------------------------------------------------
# Final Touch
#--------------------------------------------------------------------------
#

# COPY xdebug config
COPY ./xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini

# Set Timezone
RUN ln -snf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime && echo Asia/Jakarta > /etc/timezone

COPY config/php-fpm.conf /usr/local/etc/
COPY config/php.ini /usr/local/etc/php/
COPY config/www.conf /usr/local/etc/php-fpm.d/

RUN usermod -u 1000 www-data

WORKDIR /var/www

CMD ["php-fpm"]

EXPOSE 9000
