version: '3'

services:

### Workspace Utilities Container ###########################

    workspace:
      hostname: workspace
      image: mbakmia.idnmedia.io/dockerfile/workspace:${PHP_VERSION}
      volumes:
        - ${APPLICATION_DIRECTORY}:/var/www
      extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"
        ### IDN Times ###
        - "api.idntimes.local:${DOCKER_HOST_IP}"
        - "community.idntimes.local:${DOCKER_HOST_IP}"
        - "community-api.idntimes.local:${DOCKER_HOST_IP}"
        - "cms.fortuneidn.local:${DOCKER_HOST_IP}"
        - "contributor.idntimes.local:${DOCKER_HOST_IP}"
        - "cron.idntimes.local:${DOCKER_HOST_IP}"
        - "external-api.idntimes.local:${DOCKER_HOST_IP}"
        - "general-api.idntimes.local:${DOCKER_HOST_IP}"
        - "fyi.idntimes.local:${DOCKER_HOST_IP}"
        - "horizon.idntimes.local:${DOCKER_HOST_IP}"
        - "idntimes.local:${DOCKER_HOST_IP}"
        - "log-api.idntimes.local:${DOCKER_HOST_IP}"
        - "mobile-api.idntimes.local:${DOCKER_HOST_IP}"
        - "moderator.idntimes.local:${DOCKER_HOST_IP}"
        - "olimpiade.idntimes.local:${DOCKER_HOST_IP}"
        - "papaya.idntimes.local:${DOCKER_HOST_IP}"
        - "post-api.idntimes.local:${DOCKER_HOST_IP}"
        - "promo.idntimes.local:${DOCKER_HOST_IP}"
        - "qna-api.idntimes.local:${DOCKER_HOST_IP}"
        - "rabbitmq.idntimes.local:${DOCKER_HOST_IP}"
        - "redback.idntimes.local:${DOCKER_HOST_IP}"
        - "user-api.idntimes.local:${DOCKER_HOST_IP}"
        - "www.idntimes.local:${DOCKER_HOST_IP}"
        ### Duniaku ###
        - "duniaku.local:${DOCKER_HOST_IP}"
        - "otaku.idntimes.local:${DOCKER_HOST_IP}"
        - "mangaka.idntimes.local:${DOCKER_HOST_IP}"
        ### Fortune ###
        - "gatsu.fortuneidn.local:${DOCKER_HOST_IP}"
        ### Popbela ###
        - "api-cdn.popbela.local:${DOCKER_HOST_IP}"
        - "external-api.popbela.local:${DOCKER_HOST_IP}"
        - "forum-api.popbela.local:${DOCKER_HOST_IP}"
        - "fyi.popbela.local:${DOCKER_HOST_IP}"
        - "mobile-api.popbela.local:${DOCKER_HOST_IP}"
        - "log-api.popbela.local:${DOCKER_HOST_IP}"
        - "post-api.popbela.local:${DOCKER_HOST_IP}"
        - "user-api.popbela.local:${DOCKER_HOST_IP}"
        - "api.popbela-v2.local:${DOCKER_HOST_IP}"
        - "jasmine.popbela.local:${DOCKER_HOST_IP}"
        ### Popmama ###
        - "api.popmama.local:${DOCKER_HOST_IP}"
        - "cron.popmama.local:${DOCKER_HOST_IP}"
        - "hikaru.popmama.local:${DOCKER_HOST_IP}"
        - "internal-api.popmama.local:${DOCKER_HOST_IP}"
        - "komugi.popmama.local:${DOCKER_HOST_IP}"
        - "myaccount.popmama.local:${DOCKER_HOST_IP}"
        - "www.popmama.local:${DOCKER_HOST_IP}"
        ### Yummy ###
        - "community-api.yummy.local:${DOCKER_HOST_IP}"
        - "recipe-api.yummy.local:${DOCKER_HOST_IP}"
        - "user-api.yummy.local:${DOCKER_HOST_IP}"
      ports:
        - "${WORKSPACE_SSH_PORT}:22"
      networks:
        - frontend
        - backend

### PHP-FPM Container #######################################

    php-fpm:
      hostname: php-fpm
      image: mbakmia.idnmedia.io/dockerfile/php-fpm:${PHP_VERSION}
      volumes:
        - /mnt/c/Users/idnti/IDN-Media/Repos/dockerfile/laravel/php-fpm/config/php.ini:/usr/local/etc/php/php.ini
        - ${APPLICATION_DIRECTORY}:/var/www
      expose:
        - "9000"
      extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"
        ### IDN Times ###
        - "api.idntimes.local:${DOCKER_HOST_IP}"
        - "community.idntimes.local:${DOCKER_HOST_IP}"
        - "community-api.idntimes.local:${DOCKER_HOST_IP}"
        - "cms.fortuneidn.local:${DOCKER_HOST_IP}"
        - "contributor.idntimes.local:${DOCKER_HOST_IP}"
        - "cron.idntimes.local:${DOCKER_HOST_IP}"
        - "external-api.idntimes.local:${DOCKER_HOST_IP}"
        - "general-api.idntimes.local:${DOCKER_HOST_IP}"
        - "fyi.idntimes.local:${DOCKER_HOST_IP}"
        - "horizon.idntimes.local:${DOCKER_HOST_IP}"
        - "idntimes.local:${DOCKER_HOST_IP}"
        - "log-api.idntimes.local:${DOCKER_HOST_IP}"
        - "mobile-api.idntimes.local:${DOCKER_HOST_IP}"
        - "moderator.idntimes.local:${DOCKER_HOST_IP}"
        - "olimpiade.idntimes.local:${DOCKER_HOST_IP}"
        - "papaya.idntimes.local:${DOCKER_HOST_IP}"
        - "post-api.idntimes.local:${DOCKER_HOST_IP}"
        - "promo.idntimes.local:${DOCKER_HOST_IP}"
        - "qna-api.idntimes.local:${DOCKER_HOST_IP}"
        - "rabbitmq.idntimes.local:${DOCKER_HOST_IP}"
        - "redback.idntimes.local:${DOCKER_HOST_IP}"
        - "user-api.idntimes.local:${DOCKER_HOST_IP}"
        - "www.idntimes.local:${DOCKER_HOST_IP}"
        ### Duniaku ###
        - "duniaku.local:${DOCKER_HOST_IP}"
        - "otaku.idntimes.local:${DOCKER_HOST_IP}"
        - "mangaka.idntimes.local:${DOCKER_HOST_IP}"
        ### Fortune ###
        - "gatsu.fortuneidn.local:${DOCKER_HOST_IP}"
        ### Popbela ###
        - "api-cdn.popbela.local:${DOCKER_HOST_IP}"
        - "external-api.popbela.local:${DOCKER_HOST_IP}"
        - "forum-api.popbela.local:${DOCKER_HOST_IP}"
        - "fyi.popbela.local:${DOCKER_HOST_IP}"
        - "mobile-api.popbela.local:${DOCKER_HOST_IP}"
        - "log-api.popbela.local:${DOCKER_HOST_IP}"
        - "post-api.popbela.local:${DOCKER_HOST_IP}"
        - "user-api.popbela.local:${DOCKER_HOST_IP}"
        - "api.popbela-v2.local:${DOCKER_HOST_IP}"
        - "jasmine.popbela.local:${DOCKER_HOST_IP}"
        ### Popmama ###
        - "api.popmama.local:${DOCKER_HOST_IP}"
        - "cron.popmama.local:${DOCKER_HOST_IP}"
        - "hikaru.popmama.local:${DOCKER_HOST_IP}"
        - "internal-api.popmama.local:${DOCKER_HOST_IP}"
        - "komugi.popmama.local:${DOCKER_HOST_IP}"
        - "myaccount.popmama.local:${DOCKER_HOST_IP}"
        - "www.popmama.local:${DOCKER_HOST_IP}"
        ### Yummy ###
        - "community-api.yummy.local:${DOCKER_HOST_IP}"
        - "recipe-api.yummy.local:${DOCKER_HOST_IP}"
        - "user-api.yummy.local:${DOCKER_HOST_IP}"
      environment:
        - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
      networks:
        - backend

### NGINX Server Container ##################################

    nginx:
      hostname: nginx
      image: mbakmia.idnmedia.io/dockerfile/nginx:latest
      volumes:
        - ${APPLICATION_DIRECTORY}:/var/www
        - ${NGINX_CONFIG_PATH}:/etc/nginx
        - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      ports:
        - "${NGINX_HOST_HTTP_PORT}:80"
        - "${NGINX_HOST_HTTPS_PORT}:443"
      depends_on:
        - php-fpm
      networks:
        - frontend
        - backend
      extra_hosts:
        - "wsl_host:${WSL_HOST}"

### MySQL Container #########################################

    mysql:
      hostname: mysql
      image: mbakmia.idnmedia.io/dockerfile/mysql:${MYSQL_VERSION}
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      volumes:
        - /mnt/c/Users/idnti/IDN-Media/Repos/dockerfile/laravel/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        - ${DATA_SAVE_PATH}/mysql:/var/lib/mysql
        - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      ports:
        - "${MYSQL_PORT}:3306"
      networks:
        - backend

### MongoDB Container #######################################

    mongo:
      hostname: mongo
      image: mbakmia.idnmedia.io/dockerfile/mongo:latest
      ports:
        - "${MONGODB_PORT}:27017"
      volumes:
        - /data/db
      networks:
        - backend

### Redis Container #########################################

    redis:
      hostname: redis
      image: mbakmia.idnmedia.io/dockerfile/redis:latest
      volumes:
        - ${DATA_SAVE_PATH}/redis:/data
      ports:
        - "${REDIS_PORT}:6379"
      networks:
        - backend

### MailDev Container #######################################

    maildev:
      hostname: maildev
      image: mbakmia.idnmedia.io/dockerfile/maildev:latest
      ports:
        - "${MAILDEV_HTTP_PORT}:80"
        - "${MAILDEV_SMTP_PORT}:25"
      networks:
        - frontend
        - backend

### Networks Setup ############################################

networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"

### Volumes Setup #############################################

volumes:
  mysql:
    driver: local
  redis:
    driver: local
  mariadb:
    driver: local
  phpmyadmin:
    driver: local
  mongo:
    driver: local
