#
#--------------------------------------------------------------------------
# Image Setup
#--------------------------------------------------------------------------
#

FROM node:carbon-alpine

MAINTAINER Donny Arieffian <donny.arieffian@gmail.com>

# EXPOSE 8080
