apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: nginx-config-dir-0001-claim
  name: nginx-config-dir-0001-claim
spec:
  storageClassName: nginx-config-0001
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
