apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.3.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  ports:
  - name: "3080"
    port: 3080
    targetPort: 80
  - name: "3443"
    port: 3443
    targetPort: 443
  selector:
    io.kompose.service: nginx
status:
  loadBalancer: {}
