kind: PersistentVolume
apiVersion: v1
metadata:
  name: app-dir-0001
  labels:
    type: local
spec:
  storageClassName: app-dir-0001
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/Users/donny/Sites/idntimes/idntimes.com"