apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: php-fpm-app-dir-0001-claim
  name: php-fpm-app-dir-0001-claim
spec:
  storageClassName: app-dir-0001
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
status: {}
