apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.3.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: php-fpm
  name: php-fpm
spec:
  clusterIP: None
  ports:
  - name: "9000"
    port: 9000
    targetPort: 0
  selector:
    io.kompose.service: php-fpm
status:
  loadBalancer: {}
