apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.3.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nginx
    spec:
      containers:
      - image: localhost:5000/nginx-webserver:stable
        name: nginx
        resources: {}
        volumeMounts:
        - mountPath: /var/www
          name: app-dir-0001-claim
        - mountPath: /etc/nginx
          name: nginx-config-dir-0001-claim
        - mountPath: /var/log/nginx
          name: nginx-logs-dir-0001-claim
      restartPolicy: Always
      volumes:
      - name: app-dir-0001-claim
        persistentVolumeClaim:
          claimName: app-dir-0001-claim
      - name: nginx-config-dir-0001-claim
        persistentVolumeClaim:
          claimName: nginx-config-dir-0001-claim
      - name: nginx-logs-dir-0001-claim
        persistentVolumeClaim:
          claimName: nginx-logs-dir-0001-claim
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.3.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: http
  - name: "https"
    port: 443
    targetPort: https
  selector:
    io.kompose.service: nginx
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.3.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: php-fpm
  name: php-fpm
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: php-fpm
    spec:
      containers:
      - image: localhost:5000/php-fpm:stable
        name: php-fpm
        resources: {}
        volumeMounts:
        - mountPath: /var/www
          name: app-dir-0001-claim
      restartPolicy: Always
      volumes:
      - name: app-dir-0001-claim
        persistentVolumeClaim:
          claimName: app-dir-0001-claim
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.3.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: php-fpm
  name: php-fpm
spec:
  clusterIP: None
  ports:
  - name: "fpm"
    port: 9000
  selector:
    io.kompose.service: php-fpm
status:
  loadBalancer: {}