kind: PersistentVolume
apiVersion: v1
metadata:
  name: app-dir-0001
  labels:
    type: local
spec:
  storageClassName: app-dir-0001
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/Users/donny/Sites/idntimes/idntimes.com"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: nginx-config-0001
  labels:
    type: local
spec:
  storageClassName: nginx-config-0001
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/Users/donny/Docker/base/webserver/nginx-config-dev"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: nginx-logs-dir-0001
  labels:
    type: local
spec:
  storageClassName: nginx-logs-dir-0001
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/Users/donny/Docker/base/webserver/logs/nginx"

