version: '3'

services:

### PHP-FPM #############################

    php-fpm:
      image: php-fpm:stable
      volumes:
        - ${APPLICATION_DIRECTORY}:/var/www
      expose:
        - "9000"
      extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"
      networks:
        - backend

### NGINX ##################################

    nginx:
      image: nginx-webserver:stable
      volumes:
        - ${APPLICATION_DIRECTORY}:/var/www
        - ${NGINX_CONFIG_PATH}:/etc/nginx
        - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      ports:
        - "${NGINX_HOST_HTTP_PORT}:80"
        - "${NGINX_HOST_HTTPS_PORT}:443"
      depends_on:
        - php-fpm
      networks:
        - frontend
        - backend
      links:
        - php-fpm

### Networks Setup ############################################

networks:
  frontend:
    driver: "overlay"
  backend:
    driver: "overlay"
